### ISSUE TITLE
Inconsistent I/O approach

### ISSUE THREAD

**Issue by 0Xellos** [ZJULearning/nsg#1]
"Because there is no unified format for input data, users may need to write input function to read your own data."

This doesn't hold for the call Build() -> Load_nn_graph(). If I want to make a wrapper for class IndexNSG that deals with my own I/O, I can't use Build() and overload Load_nn_graph() to do nothing, which is the simplest solution. (The other alternative is copypasting Build() and deleting the call to Load_nn_graph(), which is bad practice.)

This problem should be fixed by making IndexNSG::Load_nn_graph() virtual.

Another possible solution is not calling Load_nn_graph if parameter nn_graph_path doesn't exist.

**Comment by CongFu92** [comment]
Thank you for your advice, we have modified the code.
