### ISSUE TITLE
Provide Python interface

### ISSUE THREAD

**Issue by impredicative** [ZJULearning/nsg#13]
Is it possible to provide a Python 3 interface to NSG? Thanks.

**Comment by DelightRun** [comment]
This will be done in the future, but currently we are short of hands.
We will be very appreciate if you are willing to give us a hand.

**Comment by impredicative** [comment]
Someone recommended considering https://github.com/pybind/pybind11 for wrapping C++ code for Python. I am just sharing it. Here is a [use case](https://dmtn-014.lsst.io/).

**Comment by DelightRun** [comment]
@impredicative I will look into it, thank you for your advice.
