### ISSUE TITLE
Compile errors when running make -j

### ISSUE THREAD

**Issue by GertjanBrouwer** [ZJULearning/nsg#16]
Hi,

I am trying to compile, I am following the 4 steps in the README. This unfortunately does not work for me. 
This is the output I get: [pastebin](https://pastebin.com/rzui5LQ4) . What should I do different?

**Comment by DelightRun** [comment]
Looks like something wrong with SSE instructions. What OS and compiler do you use?

**Comment by GertjanBrouwer** [comment]
I am running Ubuntu server 16.04 LTS. I only installed the packages you listed, I assume the g++ package contains the compiler I need? it says g++:amd64/xenial 4:5.3.1-1ubuntu1 uptodate.

**Comment by DelightRun** [comment]
Can you locate `x86intrin.h` header file under the path like `/usr/lib/gcc/x86_64-linux-gnu/5.3/include/x86intrin.h`? 
You can use `locate x86intrin.h` command to check this.

If not, maybe you need to install `libgcc-5-dev` as well:
```bash
$ sudo apt-get install libgcc-5-dev
```

**Comment by GertjanBrouwer** [comment]
When I type `gcc -v` it returns version 5.4.0. In the directory /usr/lib/gcc/x86_64-linux-gnu/5.4.0/include there is a file named x86intrin.h. When I install libgcc-5-dev it says I already have this installed. I also do not see any includes in the code that might need to be changed.

**Comment by GertjanBrouwer** [comment]
I also checked if my intel CPU had support for SSE2 and AVX. In /proc/cpuinfo I can find: SSE, SSE2, SSSe3, SSE4_1, SSE4_2, but not AVX.

**Comment by DelightRun** [comment]
So this is the problem. You can either use a newer CPU with AVX support or just modify the code to use SSE instead.
Maybe we can use macros to detect and choose the proper SIMD instructions.
We are short of hands for improving this project now, PRs are welcome.

**Comment by GertjanBrouwer** [comment]
I tought the code was SSE compatible? There are checks in place already.

**Comment by DelightRun** [comment]
SSE is a subset of AVX. In face we wrote this code using AVX-256 directly, and we didn't test it on SSE-only CPU (because we don't have such old CPUs). So this code cannot guarantee a backward compatibility for old SSE-only CPUs.
I'll update README to clarify this. Sorry for the inconvenient.
