### ISSUE TITLE
Why is the vector size of sift_groundtruth.ivecs, sift_query.fvecs and query results in ANN_SIFT1M different?

### ISSUE THREAD

**Issue by MrHwc** [ZJULearning/nsg#19]
Why is the vector size of sift_groundtruth.ivecs, sift_query.fvecs and query results in ANN_SIFT1M different?How to calculate precision?

**Comment by CongFu92** [comment]
For the formatting of different files, please refer to http://corpus-texmex.irisa.fr  for more details.
We use precision@K/recall@K to evaluate the results, please refer to the definition in our paper for more details.
