### ISSUE TITLE
Uninitialised variable ep_

### ISSUE THREAD

**Issue by 0Xellos** [ZJULearning/nsg#3]
The first init of `ep_` occurs at the end of `IndexNSG::init_graph`. Before that, `IndexNSG::get_neighbors` is called and uses `ep_`. This sometimes causes segfaults.

What's the intended initial value of ep_? If it's 0, it should be explicitly initialised to 0 (default behaviour in this is compiler-dependent, but there's no guarantee it will be initialised to 0 automatically). If it's an arbitrary valid node index, leave it to the user by making it `protected` instead of `private`; this is my preferred solution, since `ep_` is read in `IndexNSG::Load`.

**Comment by DelightRun** [comment]
Fixed.
