### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by op-hunter** [ZJULearning/nsg#30]
in file index_nsg.cpp:394
```
SimpleNeighbor *cut_graph_ = new SimpleNeighbor[nd_ * (size_t)range];
```
the space of cut_graph_  does not be deleted, which leads to memory leak.

**Comment by DelightRun** [comment]
Yes, you are right. And actually there exists a few other bugs in this code.
So please **NOTE** :This code is just the code used in the experiments of NSG's paper, but not for production purpose.
