### ISSUE TITLE
logic error?

### ISSUE THREAD

**Issue by op-hunter** [ZJULearning/nsg#31]
in file index_nsg.cpp:248
```
if (pool[start].id == q) start++;
```
in file index_nsg.cpp:251
```
while (result.size() < range && (++start) < pool.size() && start < maxc) {
```

if line 248 executed, it may have influence on line 251, the times of loop is not exact maxc.
so I think line 248 should be:
```
if (pool[start].id == q) start++, maxc ++;
```

**Comment by DelightRun** [comment]
It is not necessary for the times of loop to be `maxc` exactly, we are only want to make sure it will not exceed `maxc`, in case the `pool.size()` is too large to slow down the search process.
Larger `maxc` may lead to more accurate result, but with more search time.
