### ISSUE TITLE
NSG on Deep100m dataset

### ISSUE THREAD

**Issue by ghost** [ZJULearning/nsg#33]
Hi, I want to run NSG on Deep100m dataset.
Would you kindly send me the link to the dataset, please?
Also, can you share Faiss, efanna refine, SSG/NSG config for Deep100m?
Thanks,

**Comment by DelightRun** [comment]
Hi @hjbc0921,

Deep100M dataset is generated from Deep1B, you can just use the first 100M data points of Deep1B as base set. Some nice guy has publish one at [this repo](https://github.com/matsui528/deep1b_gt).

The experiment configs are as follows:

+ FAISS: IVF with 1024 inverted lists, and 96 quantifiers with 8 bytes each for the PQ codebook.
+ NSG: L = 200, R = 40.
+ SSG: L = 500, R = 40, alpha = 60 degree, m = 10
