### ISSUE TITLE
IndexNSG

### ISSUE THREAD

**Issue by MyJessie** [ZJULearning/nsg#7]
IndexNSG类中变量未初始化，在执行test_nsg_search时index_nsg.cpp    81行抛出异常。

**Comment by CongFu92** [comment]
我不知道你具体的运行状况，但看了下代码，大概是你没给好参数吧？应该是参数L没有正确赋值？

**Comment by CongFu92** [comment]
还有一种可能是你没读对图数据，所以希望你再看看文档里的介绍吧
