### ISSUE TITLE
How to choose parameters

### ISSUE THREAD

**Issue by vdv1g16** [ZJULearning/nsg#8]
I have converts my images into vectors with 4096 dimension. 
The number of training data is around 200,000 pictures. 
To build graph in NSG, need to set the default parameters, including:
- L controls the quality of the NSG, the larger the better, L > R.
- R controls the index size of the graph, the best R is related to the intrinsic dimension of the dataset.

Could you suggest value of the parameters?

**Comment by CongFu92** [comment]
Usually, we do a brute-force search in the parameter space.
You may start with R=50 and L=100
