### ISSUE TITLE
an Error when reading binary file

### ISSUE THREAD

**Issue by s5248** [ZJULearning/nsg#9]
In file nsg/tests/test_nsg_index.cpp:9, for function load_data, you read a variable dim from the head of binary file, then move the file pointer to the end of file to get its bytes, then calculate total number of features, then move the file pointer to the begin of file. Just at this time, you have not read a variable but read the features directly, this may lead to some problem.
BTW,  thank you for sharing the source code.
Best regards,

**Comment by CongFu92** [comment]
I would suggest that you read the code carefully. The load data function would move 4 bytes ahead whenever it reads a feature vector. So there is no problem with the function.

**Comment by s5248** [comment]
Sorry,the code is absolutely right. But I would wonder why it has to keep 4 bytes before each feature, rather than just keep 4 bytes at the begin of the binary file then N features of  the same dimension dim, Thanks
